---
title: "`HTML` presentation"
author: "STREEM"
date: "September 6, 2014"
output: ioslides_presentation

---

## Using `R` In slides


```{r, echo=FALSE, message=FALSE}
library("googleVis")
```

```{r}
summary(cars)
```

## googleVis

```{r results='asis'}
df <- data.frame(label=c("A", "B", "C"), val1=c(0.10,0.13,0.14), val2=c(23,12,32))
lc <- gvisLineChart(df)
print(lc, 'chart') ## So knitr includes the html output of the chart 
```

## googleVis

```{r results='asis', eval=FALSE}
A1 <- gvisAnnotatedTimeLine(Stock, datevar="Date",
                           numvar="Value", idvar="Device",
                           titlevar="Title", annotationvar="Annotation",
                           options=list(displayAnnotations=TRUE,
                            legendPosition='newRow',
                            width=600, height=300), chartid="ATLC"
                           )
plot(A1)
```

## number 2

```{r setOptions, echo=FALSE}
options(gvis.plot.tag="chart")
```

```{r motionchartcode, results='asis'}
suppressPackageStartupMessages(library(googleVis))
plot(gvisMotionChart(Fruits, "Fruit", "Year",
                     options=list(width=600, height=400)))
```
